---
- hosts: all
  become: yes
  gather_facts: yes
  vars:
    java_packages:
      - java-1.8.0-openjdk
    jenkins_version: "2.63"
    jenkins_http_port: 8080
    jenkins_admin_username: admin
    jenkins_admin_password: admin
    jenkins_plugins:
      - envinject
      - envinject-api
      - authentication-tokens
      - bouncycastle-api
      - branch-api
      - cloudbees-folder
      - credentials-binding
      - credentials
      - display-url-api
      - docker-commons
      - docker-workflow
      - durable-task
      - git-client
      - git
      - git-server
      - handlebars
      - jackson2-api
      - jquery-detached
      - jsch
      - junit
      - mailer
      - mapdb-api
      - matrix-auth
      - matrix-project
      - momentjs
      - pipeline-build-step
      - pipeline-graph-analysis
      - pipeline-input-step
      - pipeline-milestone-step
      - pipeline-model-api
      - pipeline-model-declarative-agent
      - pipeline-model-definition
      - pipeline-model-extensions
      - pipeline-rest-api
      - pipeline-stage-step
      - pipeline-stage-tags-metadata
      - pipeline-stage-view
      - plain-credentials
      - scm-api
      - scm-sync-configuration
      - script-security
      - ssh-agent
      - ssh-credentials
      - ssh-slaves
      - ssh
      - structs
      - subversion
      - windows-slaves
      - workflow-aggregator
      - workflow-api
      - workflow-basic-steps
      - workflow-cps-global-lib
      - workflow-cps
      - workflow-durable-task-step
      - workflow-job
      - workflow-multibranch
      - workflow-scm-step
      - workflow-step-api
      - workflow-support
      - swarm
    firewall_allowed_tcp_ports:
      - 22
      - "{{ jenkins_http_port }}"
  roles:
    - geerlingguy.nfs
    - geerlingguy.packer-rhel
    - geerlingguy.git
    - geerlingguy.java
    - geerlingguy.firewall
    - geerlingguy.jenkins
