---
- name: Get Jenkins crumb
  uri:
    user: admin
    password: admin
    force_basic_auth: yes
    url: "http://127.0.0.1:16080/crumbIssuer/api/json"
    return_content: yes
    status_code: 200, 404
  register: jenkins_crumb
  until: jenkins_crumb.status == 200 and jenkins_crumb.content.find('Please wait while Jenkins is getting ready to work') == -1
  retries: 10
  delay: 5

- name: Set crumb token
  set_fact:
    jenkins_crumb_token: "{{ jenkins_crumb.json.crumbRequestField }}={{ jenkins_crumb.json.crumb }}"

- name: Creating git credential
  uri:
    method: POST
    url: 'http://127.0.0.1:16080/credentials/store/system/domain/_/createCredentials'
    user: admin
    password: admin
    force_basic_auth: yes
    headers:
      Jenkins-Crumb: "{{ jenkins_crumb.json.crumb }}"
    body: |
      json={
        "": "0",
        "credentials": {
          "scope": "GLOBAL",
          "id": "1",
          "username": "ci-system-user",
          "password": "mb123qwe",
          "description": "CI GitHub System User",
          "$class": "com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl"
        }
      }
    status_code: 302

- include_tasks: seed-main-job.yml
- include_tasks: seed-infrastructure-job.yml
- include_tasks: seed-infrastructure-clean-job.yml
- include_tasks: seed-infrastructure-ci-job.yml