Vagrant.configure(2) do |config|
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', type: 'nfs'
  config.vm.box = "file://centos7-ci-virtualbox.box"
  config.vm.network :private_network, ip: "172.16.3.2"
  config.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
  config.vm.provider :virtualbox do |v|
    v.gui = false
    v.memory = 1024
    v.cpus = 1
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end
  config.vm.provision "shell", inline: "echo Hello, World"
end
