Vagrant.configure(2) do |config|
  config.ssh.insert_key = false
  config.vm.synced_folder './vm_resources', '/vagrant', type: 'rsync'
  config.vm.provider :virtualbox do |vb, override|
    vb.gui = false
    vb.memory = 1024
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    override.vm.box = "file://./images/centos7-ci.box"
    override.vm.network :private_network, ip: "192.168.51.128", gateway: "192.168.51.1"
    override.vm.network "forwarded_port", guest: 16080, host: 16080, auto_correct: true
    override.vm.network "forwarded_port", guest: 16081, host: 16081, auto_correct: true
  end
  config.vm.provider :azure do |azure, override|
    azure.tenant_id = ENV['ARM_TENANT_ID']
    azure.client_id = ENV['ARM_CLIENT_ID']
    azure.client_secret = ENV['ARM_CLIENT_SECRET']
    azure.subscription_id = ENV['ARM_SUBSCRIPTION_ID']
    azure.vm_managed_image_id = '/subscriptions/7bff593e-4ee7-40bb-9d2b-522f196626e5/resourceGroups/CommonRG/providers/Microsoft.Compute/images/centos7-ci'
    azure.vm_name = 'spdvpsstrtrci'
    azure.location = 'WestUS2'
    azure.vm_size = 'Standard_B1s'
    azure.vm_storage_account_type = 'Standard_LRS'
    azure.wait_for_destroy = true
    azure.tcp_endpoints = ['16080', '16081']
    override.vm.box = "azure"
    override.ssh.private_key_path = 'C:\HashiCorp\Vagrant\embedded\gems\2.1.1\gems\vagrant-2.1.1\keys\vagrant'
  end
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "ansible/main.yml"
  end
end
